/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountAdvSearch: typeof import('./src/components/Accounts/AccountAdvSearch.vue')['default']
    AccountsDetail: typeof import('./src/components/Accounts/AccountsDetail.vue')['default']
    AccountsList: typeof import('./src/components/Accounts/AccountsList.vue')['default']
    BrandBar: typeof import('./src/components/BrandBar.vue')['default']
    BreakPoints: typeof import('./src/components/BreakPoints.vue')['default']
    CheckboxInput: typeof import('./src/components/Inputs/CheckboxInput.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DetailMain: typeof import('./src/components/DetailMain.vue')['default']
    FooterBox: typeof import('./src/components/FooterBox.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    IconSymbol: typeof import('./src/components/IconSymbol.vue')['default']
    IntroView: typeof import('./src/components/IntroView.vue')['default']
    LayoutLogin: typeof import('./src/layouts/LayoutLogin.vue')['default']
    LayoutMain: typeof import('./src/layouts/LayoutMain.vue')['default']
    ListPager: typeof import('./src/components/ListPager.vue')['default']
    ListPagerDebugger: typeof import('./src/components/ListPagerDebugger.vue')['default']
    LoginPopout: typeof import('./src/components/LoginPopout.vue')['default']
    ModalControl: typeof import('./src/components/ModalControl.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavTab: typeof import('./src/components/NavTab.vue')['default']
    PasswordInput: typeof import('./src/components/Inputs/PasswordInput.vue')['default']
    PhoneInput: typeof import('./src/components/Inputs/PhoneInput.vue')['default']
    ReverseCorner: typeof import('./src/components/ReverseCorner.vue')['default']
    RotateButton: typeof import('./src/components/RotateButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./src/components/Inputs/SelectInput.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SiteMap: typeof import('./src/components/SiteMap.vue')['default']
    SubNavBar: typeof import('./src/components/SubNavBar.vue')['default']
    SwitchButton: typeof import('./src/components/SwitchButton.vue')['default']
    TextInput: typeof import('./src/components/Inputs/TextInput.vue')['default']
    UsersDetail: typeof import('./src/components/Admin/UsersDetail.vue')['default']
    UsersList: typeof import('./src/components/Admin/UsersList.vue')['default']
  }
}
