@coreApi.Server_HostAddress = https://localhost:9999

### ====================================================================
### For Authentication use login below
### ====================================================================

# @name login
POST {{coreApi.Server_HostAddress}}/v1/authenticate/login
accept: */* 
Content-Type: application/json

{
	"username": "testuser",
	"password": "Test123!"
}

### me - Get current user claims =========================================

GET {{coreApi.Server_HostAddress}}/v1/authenticate/me
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

### saveAccount ==========================================================
POST {{coreApi.Server_HostAddress}}/v1/accounts/saveAccount
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
	"AccountName": "Test Account",
	"AccountEmail": "wtest@test.com",
	"AccountPhone": "(404) 333 4444",
	"StreetAddress": "123 Street St.",
	"City": "New York",
	"StateProvince": "NY",
	"PostalCode": "12345"
}

### getAllUsers  ======================================================

GET {{coreApi.Server_HostAddress}}/v1/users/getAllUsers
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

### getPagedUserss  ==================================================

POST {{coreApi.Server_HostAddress}}/v1/users/getPagedUsers
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
  "currentRecord": 0,
  "pageSize": 20,
  "groupSize": 5,
  "search": {
    "filter": "Will",
    "filterType": "",
    "sort": "",
    "sortDesc": true,
    "roleFilter": "Admin"
  }
}

### getPagedAccounts  ==================================================

POST {{coreApi.Server_HostAddress}}/v1/accounts/getPagedAccounts
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
  "currentRecord": 0,
  "pageSize": 20,
  "groupSize": 5,
  "search": {
    "filter": "Cap",
    "filterType": "",
    "sort": "",
    "sortDesc": true,
    "stateProvinceFilter": "",
    "postalCodeFilter": ""
  }
}

### getAllAccounts   ====================================================

GET {{coreApi.Server_HostAddress}}/v1/accounts/getAllAccounts
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

### SIGN UP USER   ======================================================

POST {{coreApi.Server_HostAddress}}/v1/authenticate/signup
Content-Type: application/json
Accept: application/json

{  
	"UserName": "wtest117@test.com",
	"Password": "Test123!",
	"FirstName": "Will",
	"LastName": "Test117",
	"UserEmail": "willTest117@gmail.com",
	"Role": "User"
}

### =====================================================================
