@coreApi.Server_HostAddress = https://localhost:9999


### FOR AUTHENTICATION LOGIN HERE !
# @name login
POST {{coreApi.Server_HostAddress}}/v1/authenticate/login
accept: */* 
Content-Type: application/json

{
	"username": "wcrowther22",
	"password": "Test123!"
}

###
POST {{coreApi.Server_HostAddress}}/v1/accounts/saveAccount
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json

{
	"AccountName": "Test Account",
	"AccountEmail": "wtest@test.com",
	"AccountPhone": "(404) 333 4444",
	"StreetAddress": "123 Street St.",
	"City": "New York",
	"StateProvince": "NY",
	"PostalCode": "12345"
}

###

GET {{coreApi.Server_HostAddress}}/v1/users/getAllUsers
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json


###

GET {{coreApi.Server_HostAddress}}/v1/accounts/getAllAccounts
Authorization: bearer {{login.response.body.$.token}}
Content-Type: application/json
Accept: application/json


### SIGN UP USER

POST {{coreApi.Server_HostAddress}}/v1/authenticate/signup
Content-Type: application/json
Accept: application/json

{  
	"UserName": "wtest117@test.com",
	"Password": "Test123!",
	"FirstName": "Will",
	"LastName": "Test117",
	"UserEmail": "willTest117@gmail.com",
	"Role": "User"
}