export const examplesDataList =
    [
        { name: 'Accordion', example: 'AccordionExample', show: false, featured: false, type: '', order: 5},
        { name: 'Calendar', example: 'CalendarExample', show: true, featured: false, type: '', order: 5},
        { name: 'Checkers', example: 'CheckersExample', show: true, featured: true, type: '', order: 5},
        { name: 'Composables', example: 'ComposablesExample', show: true, featured: false, type: '', order: 5},
        { name: 'ConwaysLife', example: 'ConwaysLifeExample', show: true, featured: true, type: '', order: 5},
        { name: 'DetailBox', example: 'DetailBoxExample', show: true, featured: false, type: '', order: 5},
        { name: 'Content', example: 'ContentExample', show: true, featured: true, type: '', order: 5},
        { name: 'ContextMenu', example: 'ContextMenuExample', show: true, featured: false, type: '', order: 5},
        { name: 'Floater', example: 'FloaterExample', show: true, featured: false, type: '', order: 5},
        { name: 'FullScreen', example: 'FullScreenExample', show: true, featured: false, type: '', order: 5},
        { name: 'Grid', example: 'GridExample', show: true, featured: false, type: '', order: 5},
        { name: 'ImageCropper', example: 'ImageCropperExample', show: true, featured: false, type: '', order: 5},
        { name: 'Inputs', example: 'InputsExample', show: true, featured: true, type: '', order: 2},
        { name: 'Intro', example: 'IntroToExamples', show: true, featured: true, type: '', order: 1},
        { name: 'JsonTree', example: 'JsonTreeExample', show: true, featured: false, type: '', order: 5},
        { name: 'Buttons', example: 'ButtonsExample', show: true, featured: false, type: '', order: 5},
        { name: 'Misc', example: 'MiscExample', show: false, featured: false, type: '', order: 5},
        { name: 'ModalControl', example: 'ModalControlExample', show: true, featured: false, type: '', order: 5},
        { name: 'MultiSelect', example: 'MultiSelectExample', show: true, featured: false, type: '', order: 5},
        { name: 'PanZoom', example: 'PanZoomExample', show: true, featured: false, type: '', order: 5},
        { name: 'TabsFlowBar', example: 'TabsFlowBarExample', show: false, featured: false, type: '', order: 5},
        { name: 'TabsControl', example: 'TabsControlExample', show: true, featured: false, type: '', order: 5},
        { name: 'TabsFlowControl', example: 'TabsFlowExample', show: true, featured: false, type: '', order: 5},
        { name: 'Wizard', example: 'WizardExample', show: true, featured: false, type: '', order: 5},
    ]